name: Publish to AWS on push
run-name: Push by ${{ github.actor }} publishing to AWS

on: [push]
jobs:
  publish-project:
    runs-on: ubuntu-latest
    environment: prod
    
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build the sources
        run: npm run build --if-present
      - name: Deploy 
        uses: easingthemes/ssh-deploy@main
        with:
            SSH_PRIVATE_KEY: |
              ${{ secrets.AWS_SSH_KEY }}
            ARGS: "-rlgoDzvc -i"
            SOURCE: "./"
            REMOTE_HOST: ${{secrets.AWS_REMOTE_HOST}}
            REMOTE_USER: ${{secrets.AWS_REMOTE_USER}}
            TARGET: ${{secrets.AWS_REMOTE_TARGET}}
            EXCLUDE: "/node_modules/, /.git/, /.github/"  
