name: Run tests in Linux on push
run-name: Push by ${{ github.actor }} is testing 🚀
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Starting tests
        run: |
          npm install
          npm run test
